apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox
  namespace: hivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
        - name: hivebox
          image: ghcr.io/raniaafath/devops-hands-on-project-hivebox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: hivebox-config
          livenessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
